# Generated by Django 3.2 on 2021-09-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
