# Generated by Django 3.2 on 2021-06-15 15:16

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hackathons.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_remove_organization_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField(default='')),
                ('tag_line', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('contact_email', models.EmailField(default='', max_length=254)),
                ('theme_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25), default=list, size=None)),
                ('participant_age_required', models.IntegerField(default=1)),
                ('is_team_required', models.BooleanField(default=False)),
                ('rules', models.TextField(default='')),
                ('resource', models.TextField(default='')),
                ('submission_requirement', models.TextField(default='')),
                ('community_chat', models.URLField(default='')),
                ('start_of_hackathon', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_of_hackathon', models.DateTimeField(default=django.utils.timezone.now)),
                ('upload_file_type', models.CharField(default='', max_length=25)),
                ('is_video_required', models.BooleanField(default=False)),
                ('is_public_voting_enable', models.BooleanField(default=False)),
                ('start_of_judging', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_of_judging', models.DateTimeField(default=django.utils.timezone.now)),
                ('result_announcement_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('prize_currency', models.CharField(default='', max_length=25)),
                ('saved_type', models.CharField(choices=[('PUBLISHED', 'PUBLISHED'), ('DRAFT', 'DRAFT')], default='DRAFT', max_length=10)),
                ('thumbnail_image', models.ImageField(default='', upload_to=hackathons.models.Hackathon.get_thumbnail_image_path)),
                ('logo_image', models.ImageField(default='', upload_to=hackathons.models.Hackathon.get_logo_image_path)),
                ('background_image', models.ImageField(default='', upload_to=hackathons.models.Hackathon.get_background_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hackathon', to='user.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=25)),
                ('logo', models.ImageField(default='', upload_to=hackathons.models.Sponsor.get_image_path)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='hackathons.hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=25)),
                ('value', models.IntegerField()),
                ('no_of_winning_projects', models.IntegerField()),
                ('description', models.TextField()),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='hackathons.hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.TextField()),
                ('photo', models.ImageField(default='', upload_to=hackathons.models.Judge.get_image_path)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judges', to='hackathons.hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='hackathons.hackathon')),
            ],
        ),
    ]
