# Generated by Django 3.2 on 2021-12-11 16:41

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import hackathons.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0016_auto_20211211_0536'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField(default='')),
                ('tag_line', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('theme_tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('rules', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('resource', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('submission_requirement', models.TextField(default='')),
                ('logo_image', models.ImageField(blank=True, default='', upload_to=hackathons.models.Hackathon.get_logo_image_path)),
                ('background_image', models.ImageField(blank=True, default='', upload_to=hackathons.models.Hackathon.get_background_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hackathon', to='user.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('tag_line', models.TextField(default='')),
                ('about', models.TextField(default='')),
                ('built_with', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default='', max_length=25), blank=True, default=list, size=None)),
                ('links', models.URLField()),
                ('video_link', models.URLField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, default='', upload_to=hackathons.models.Project.get_logo_image_path)),
                ('file', models.FileField(default='', upload_to=hackathons.models.Project.get_file_path)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='hackathons.hackathon')),
                ('student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='project', to='user.student')),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=25)),
                ('value', models.IntegerField()),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='hackathons.hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='hackathons.hackathon')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JudgingCriteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_judging_criteria', to='hackathons.hackathon')),
            ],
        ),
    ]
