# Generated by Django 3.2 on 2021-11-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='status',
            field=models.CharField(blank=True, choices=[('Upcoming', 'Upcoming'), ('Open', 'Open'), ('Ended', 'Ended')], default='Upcoming', max_length=15),
        ),
    ]
