# Generated by Django 3.2 on 2021-12-11 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='event_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
