# Generated by Django 3.2 on 2021-12-01 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0002_hackathon_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='allowed_file_types',
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='final_reminder',
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='promotional_video',
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='result_announcement_date',
        ),
        migrations.RemoveField(
            model_name='prize',
            name='perks',
        ),
    ]
