# Generated by Django 3.2 on 2021-08-21 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_organization_name'),
        ('hackathons', '0003_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hackathon_participant', serialize=False, to='user.student'),
        ),
    ]
