# Generated by Django 3.2 on 2021-12-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0004_alter_subscription_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='payment_id',
            field=models.UUIDField(),
        ),
    ]
