# Generated by Django 3.2 on 2021-12-04 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0004_auto_20211204_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='is_team_required',
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='max_team_members',
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='min_team_members',
        ),
    ]
