# Generated by Django 3.2 on 2021-10-08 22:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import hackathons.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0006_alter_share_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('tag_line', models.TextField(default='')),
                ('about', models.TextField(default='')),
                ('built_with', models.TextField(default='')),
                ('links', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None)),
                ('video_link', models.URLField()),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='hackathons.hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metadata', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('path', models.ImageField(default='', upload_to=hackathons.models.ProjectMedia.get_image_path_and_filename)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hackathons.project')),
            ],
        ),
    ]
