# Generated by Django 3.2 on 2021-12-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0006_alter_subscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
