# Generated by Django 3.2 on 2021-10-08 22:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0007_project_projectmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='built_with',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=25), size=None),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('emails', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='hackathons.hackathon')),
            ],
        ),
    ]
