# Generated by Django 3.2 on 2021-12-13 01:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0007_auto_20211213_0525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluated',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('idea', models.IntegerField(default=0)),
                ('originality', models.IntegerField(default=0)),
                ('functionality', models.IntegerField(default=0)),
                ('design', models.IntegerField(default=0)),
                ('problem', models.IntegerField(default=0)),
                ('stars', models.IntegerField(default=1)),
                ('remarks', models.TextField(default='')),
                ('project', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='hackathons.project')),
            ],
        ),
    ]
