# Generated by Django 3.2 on 2021-10-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0009_project_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='video_link',
            field=models.URLField(default=''),
        ),
    ]
