# Generated by Django 3.2 on 2021-10-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0010_alter_project_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='video_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
