# Generated by Django 3.2 on 2021-10-09 11:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0011_alter_project_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='built_with',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default='', max_length=25), size=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(default=''), size=None),
        ),
    ]
