# Generated by Django 3.2 on 2021-10-09 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackathons', '0014_auto_20211009_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hackathon_participant', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
