# Generated by Django 3.2 on 2021-11-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='is_certificate',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='working_hour',
        ),
        migrations.AddField(
            model_name='internship',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
