# Generated by Django 3.2 on 2021-11-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_auto_20211126_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='cv',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='github',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='linked_in',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='portfolio',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='resume',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
