# Generated by Django 3.2 on 2021-11-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_auto_20211128_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='portfolio',
            field=models.URLField(blank=True, default=''),
        ),
    ]
