# Generated by Django 3.2 on 2021-11-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0004_alter_participant_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='github',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='participant',
            name='linked_in',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='participant',
            name='portfolio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
