# Generated by Django 3.2 on 2021-11-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0005_auto_20211128_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='github',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='participant',
            name='linked_in',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='participant',
            name='portfolio',
            field=models.URLField(blank=True, default=''),
        ),
    ]
