# Generated by Django 3.2 on 2021-12-01 18:18

from django.db import migrations, models
import internships.models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0006_auto_20211128_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='cv',
            field=models.FileField(default='', upload_to=internships.models.Participant.get_cv_file_path),
        ),
        migrations.AlterField(
            model_name='participant',
            name='resume',
            field=models.FileField(blank=True, default='', upload_to=internships.models.Participant.get_resume_file_path),
        ),
    ]
