# Generated by Django 3.2 on 2021-12-03 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0007_auto_20211201_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_meeting_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='meeting_schedule',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
