# Generated by Django 3.2 on 2021-12-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0008_auto_20211203_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='meeting_id',
            field=models.IntegerField(default=0),
        ),
    ]
