# Generated by Django 3.2 on 2021-08-10 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_one', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_one_chat', to=settings.AUTH_USER_MODEL)),
                ('user_second', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_second_chat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField(default='', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_message', to=settings.AUTH_USER_MODEL)),
                ('chat_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='chat_message', to='chat.chat')),
            ],
        ),
    ]
