# Generated by Django 3.2 on 2021-08-10 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='user_one',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_one_chat', to=settings.AUTH_USER_MODEL),
        ),
    ]
