# Generated by Django 3.2 on 2021-08-10 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_alter_chat_user_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='user_second',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_second_chat', to=settings.AUTH_USER_MODEL),
        ),
    ]
