# Generated by Django 3.2 on 2021-12-11 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_auto_20210923_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='user_first',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_first_chat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user_second',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_second_chat', to=settings.AUTH_USER_MODEL),
        ),
    ]
