# Generated by Django 3.2 on 2021-11-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sphere_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='event_date',
            new_name='end_date',
        ),
    ]
