# Generated by Django 3.2 on 2021-11-24 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0006_alter_fyp_outcomes'),
        ('sphere_engine', '0005_remove_submission_fyp'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='fyp',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='fyp.fyp'),
        ),
    ]
