# Generated by Django 3.2 on 2021-12-01 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20211005_0448'),
        ('sphere_engine', '0006_submission_fyp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='user.student'),
        ),
    ]
