# Generated by Django 3.2 on 2021-12-07 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_query'),
        ('sphere_engine', '0007_alter_submission_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='user.student'),
        ),
    ]
