# Generated by Django 3.2 on 2021-11-14 16:00

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0011_auto_20211005_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='FYP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('category', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('technologies', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('outcomes', models.TextField()),
                ('team_members', models.IntegerField()),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fyp', to='user.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fyp_participant', serialize=False, to='user.student')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('fyp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='fyp.fyp')),
            ],
        ),
    ]
