# Generated by Django 3.2 on 2021-11-14 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fyp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fyp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fyp', to=settings.AUTH_USER_MODEL),
        ),
    ]
