# Generated by Django 3.2 on 2021-11-14 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20211005_0448'),
        ('fyp', '0002_alter_fyp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fyp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fyp', to='user.organization'),
        ),
    ]
