# Generated by Django 3.2 on 2021-11-14 17:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0003_alter_fyp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fyp',
            name='outcomes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
    ]
