# Generated by Django 3.2 on 2021-11-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0004_alter_fyp_outcomes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fyp',
            name='team_members',
            field=models.IntegerField(default=1),
        ),
    ]
