# Generated by Django 3.2 on 2021-11-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0005_alter_fyp_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fyp',
            name='outcomes',
            field=models.TextField(),
        ),
    ]
