# Generated by Django 3.2 on 2021-12-02 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_query'),
        ('fyp', '0006_alter_fyp_outcomes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fyp_participant', serialize=False, to='user.student'),
        ),
    ]
