# Generated by Django 3.2 on 2021-12-13 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0008_auto_20211202_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_meeting_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='meeting_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='meeting_schedule',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
