# Generated by Django 3.2 on 2021-12-19 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0010_participant_join_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fyp',
            name='team_members',
        ),
    ]
