# Generated by Django 3.2 on 2021-08-21 15:01

from django.db import migrations, models
import django.db.models.deletion
import uuid
import workshop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_organization_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('poster', models.ImageField(default='', upload_to=workshop.models.Workshop.get_workshop_image_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workshop', to='user.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='workshop_participant', serialize=False, to='user.student')),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='workshop.workshop')),
            ],
        ),
    ]
