# Generated by Django 3.2 on 2021-11-06 12:34

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid
import workshop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0011_auto_20211005_0448'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('poster', models.ImageField(default='', upload_to=workshop.models.Workshop.get_workshop_image_path)),
                ('take_away', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('event_date', models.DateField(default=datetime.date.today)),
                ('start_time', models.TimeField(default=datetime.time)),
                ('end_time', models.TimeField(default=datetime.time)),
                ('is_paid', models.BooleanField(default=False)),
                ('charges', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop', to='user.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='workshop_schedule', serialize=False, to='workshop.workshop')),
                ('time', models.TimeField(default=datetime.time)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(default='', upload_to=workshop.models.Speaker.get_image_path)),
                ('about', models.TextField()),
                ('social_links', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, size=None)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker', to='workshop.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_share', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='workshop.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='PreRequisite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=40)),
                ('list', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_prerequisite', to='workshop.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='workshop_participant', serialize=False, to='user.student')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='workshop.workshop')),
            ],
        ),
    ]
