# Generated by Django 3.2 on 2021-11-06 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='title',
            new_name='topic',
        ),
    ]
