# Generated by Django 3.2 on 2021-11-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_rename_title_workshop_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='charges',
            field=models.IntegerField(default=0),
        ),
    ]
