# Generated by Django 3.2 on 2021-11-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_alter_workshop_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
