# Generated by Django 3.2 on 2021-11-23 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_auto_20211123_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='workshop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speaker', to='workshop.workshop'),
        ),
    ]
