# Generated by Django 3.2 on 2021-12-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_auto_20211202_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='social_links',
        ),
        migrations.AddField(
            model_name='speaker',
            name='github',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='speaker',
            name='linked_in',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='speaker',
            name='twitter',
            field=models.URLField(default=''),
        ),
    ]
