# Generated by Django 3.2 on 2021-12-08 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_auto_20211203_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker', to='workshop.workshop'),
        ),
    ]
