# Generated by Django 3.2 on 2021-12-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0009_alter_speaker_workshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='github',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='linked_in',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='twitter',
            field=models.TextField(default=''),
        ),
    ]
