# Generated by Django 3.2 on 2021-12-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0010_auto_20211208_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='join_url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='workshop',
            name='start_url',
            field=models.TextField(default=''),
        ),
    ]
