# Generated by Django 3.2 on 2021-12-08 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0011_auto_20211208_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='end_time',
        ),
    ]
