# Generated by Django 3.2 on 2021-05-25 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_organization_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='reg_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='organization',
            name='uuid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='organization', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
