# Generated by Django 3.2 on 2021-06-05 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_follower'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metadata', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('path', models.ImageField(default='', upload_to=user.models.ProfileImage.get_image_path_and_filename)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_image', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metadata', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('path', models.ImageField(default='', upload_to=user.models.BackgroundImage.get_image_path_and_filename)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_background_image', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
