# Generated by Django 3.2 on 2021-06-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_backgroundimage_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='name',
        ),
    ]
