# Generated by Django 3.2 on 2021-09-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_organization_incorporation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='reg_no',
            field=models.CharField(max_length=80),
        ),
    ]
