# Generated by Django 3.2 on 2021-10-04 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20211005_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bio',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='student',
            name='education',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='student',
            name='github',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='linked_in',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='lives_in',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='portfolio',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='twitter',
            field=models.URLField(blank=True, default=''),
        ),
    ]
