# Generated by Django 3.2 on 2021-12-10 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
    ]
