# Generated by Django 3.2 on 2021-12-11 00:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20211211_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default=list, max_length=50), size=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default=list, max_length=50), size=None),
        ),
    ]
